--- thirdparty/darknet/Makefile	2019-06-13 05:27:23.181448284 +0900
+++ scripts/darknet/Makefile	2019-06-13 05:26:20.180463527 +0900
@@ -1,9 +1,9 @@
-GPU=0
-CUDNN=0
-CUDNN_HALF=0
-OPENCV=0
+GPU=1
+CUDNN=1
+CUDNN_HALF=1
+OPENCV=1
 AVX=0
-OPENMP=0
+OPENMP=1
 LIBSO=0
 ZED_CAMERA=0
 
@@ -17,7 +17,8 @@
       -gencode arch=compute_35,code=sm_35 \
       -gencode arch=compute_50,code=[sm_50,compute_50] \
       -gencode arch=compute_52,code=[sm_52,compute_52] \
-	  -gencode arch=compute_61,code=[sm_61,compute_61]
+      -gencode arch=compute_53,code=[sm_53,compute_53] \
+#  -gencode arch=compute_61,code=[sm_61,compute_61]
 
 OS := $(shell uname)
 
@@ -36,8 +37,8 @@
 # GP100/Tesla P100 - DGX-1
 # ARCH= -gencode arch=compute_60,code=sm_60
 
-# For Jetson TX1, Tegra X1, DRIVE CX, DRIVE PX - uncomment:
-# ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
+# For Jetson TX1, Tegra X1, DRIVE CX, DRIVE PX, Jetson Nano - uncomment:
+ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
 
 # For Jetson Tx2 or Drive-PX2 uncomment:
 # ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]
@@ -55,7 +56,7 @@
 CC=gcc
 CPP=g++
 NVCC=nvcc
-OPTS=-Ofast
+OPTS=-Ofast -march=native
 LDFLAGS= -lm -pthread
 COMMON= -Iinclude/ -I3rdparty/stb/include
 CFLAGS=-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC
